### ISSUE TITLE
Headless processing failed

### ISSUE THREAD

**Issue by gabrielpan147** [embl-cba/ICS#25]
Hello,

I tried to use the headless mode of the plug-in on Ubuntu. I ran the plugin with the command line
 `ImageJ-linux64 --headless --run "Process BD CellView Images Headless" "settingsFile='/mnt/data/gabrielpan/BDS8/BDS8_demo_data/batch_2channels.json'"` 
The plugin seemed to be working fine with information: 
```
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Processing table: /mnt/data/gabrielpan/BDS8/BDS8_demo_data/output/test.csv

Loading table: /mnt/data/gabrielpan/BDS8/BDS8_demo_data/output/test.csv
Loaded table in 65 ms.
Table Info
Number of rows: 10000
path: ../Sample_002/Sample_002_images_20231128_1457_19/00000000/Sample_002_00000000.tiff, ../Sample_002/Sample_002_images_20231128_1457_19/00000000/Sample_002_00000001.tiff, ../Sample_002/Sample_002_images_20231128_1457_19/00000000/Sample_002_00000002.tiff, ../Sample_002/Sample_002_images_20231128_1457_19/00000000/Sample_002_00000003.tiff, ../Sample_002/Sample_002_images_20231128_1457_19/00000000/Sample_002_00000004.tiff, ...
id: id0, id1, id2, id3, id4, ...
gate: Default, Default, Default, Default, Default, ...
Gates: Default
Selected gate: Default
Images matching gate: 10000
Saving processed images to directory: /mnt/data/gabrielpan/BDS8/BDS8_demo_data/images-processed-2024-02-21-16-37
Number of images to be processed: 10000
Files processed: 1/10000; time ( spent, left, task ) [ s ]: 0, 89, 0.00900; memory: 177MB of 187384MB (<1%)
```
However, the code then exited with no error or warning raised. And only around 10 images are processed. I tried to increased the memory used but it did not seem to help.

I would like to know if you have any idea about this issue?

**Comment by schraivo** [comment]
Hi Gabriel, sorry for the delay. We'll have a look. Can you share a dataset for us to reproduce the error? We have never seen it.

**Comment by tischi** [comment]
Hi @gabrielpan147,

yes, to debug this it would be great if you could share with us:

1. the JSON settings file
2. the table file

Thanks!

**Comment by gabrielpan147** [comment]
Hello @tischi and @schraivo,
Please find some demo data [here](https://hkustconnect-my.sharepoint.com/:u:/g/personal/epanab_connect_ust_hk/EfB0TT2bs0hLuEIv_fp5G7MBqteW5Iv_9CDAFBatJsQxDg?e=v1NiHK). I attached a demo dataset, demo table.csv file and my json file. FYI, my command used to start the processing is `ImageJ-linux64 --headless --run "Process BD CellView Images Headless" "settingsFile='/mnt/data/gabrielpan/BDS8/BDS8_demo_data/batch_2channels.json'"`, within a Ubuntu OS.

Thank you for your help!!

**Comment by tischi** [comment]
@gabrielpan147 Thanks! I am downloading...this is quite big, to speed this up, could you please also just paste the content of the JSON file here?

**Comment by gabrielpan147** [comment]
@tischi Hello, please find the json file here:
{
  "fileSizeRangeCSV": "10,100000",
  "channelIndexCSV": "1,4",
  "colorCSV": "White*,Green*",
  "showOnlyMergeInColor": true,
  "minimumGrayLevelCSV": "0.0,0.0,0.0,0.0,0.0",
  "maximumGrayLevelCSV": "1.0,1.0,1.0,1.0,1.0",
  "horizontalCropPixels": 0,
  "viewingModality": "Processed merge",
  "maxNumFiles": -1,
  "experimentDirectory": "/Users/gabrielpan/Desktop/GABRIEL/20240202_DATA",
  "selectedTableFile": {
    "path": "/Users/gabrielpan/Desktop/GABRIEL/20240202_DATA/outputs/Sample_008.csv"
  },
  "gateColumnName": "gate",
  "quitAfterRun": true,
  "selectedGate": "Default",
  "numImagesToBeProcessed": 10000
}

**Comment by tischi** [comment]
Thanks @gabrielpan147,

Hmm, this seems to be correct: `"maxNumFiles": -1,`, because that means to analyse all files.

I will have to try to reproduce your issue on my computer....I hope I will have some time tomorrow.

**Comment by tischi** [comment]
Oh, but in fact the JSON that I got from you looks different:

```
{
  "fileSizeRangeCSV": "10,100000",
  "channelIndexCSV": "1,4",
  "colorCSV": "White*,Green*",
  "showOnlyMergeInColor": true,
  "minimumGrayLevelCSV": "0.0,0.0,0.0,0.0,0.0",
  "maximumGrayLevelCSV": "1.0,1.0,1.0,1.0,1.0",
  "horizontalCropPixels": 0,
  "viewingModality": "Processed merge",
  "maxNumFiles": -1,
  "experimentDirectory": "..",
  "selectedTableFile": {
    "path": "../outputs/Sample_005.csv"
  },
  "gateColumnName": "gate",
  "quitAfterRun": true,
  "selectedGate": "Default",
  "numImagesToBeProcessed": 10000
}
```

The paths are different. Should I just adjust the paths such that they point to the correct files as they are stored on my computer?

**Comment by gabrielpan147** [comment]
Hello @tischi ,
Yes please just adjust the paths, it should be fine.
Thank you for your help!

**Comment by tischi** [comment]
For me, within the Java IDE it runs:

```
Processing table: /Users/tischer/Downloads/demo_data/outputs/Sample_005.csv

Loading table: /Users/tischer/Downloads/demo_data/outputs/Sample_005.csv
Loaded table in 365 ms.
# Table Info
Number of rows: 10000
path: ../Sample_005/Sample_005_images_20240202_1659_30/00000000/Sample_005_00006276.tiff, ../Sample_005/Sample_005_images_20240202_1659_30/00000000/Sample_005_00009183.tiff, ../Sample_005/Sample_005_images_20240202_1659_30/00000000/Sample_005_00009479.tiff, ../Sample_005/Sample_005_images_20240202_1659_30/00000000/Sample_005_00001049.tiff, ../Sample_005/Sample_005_images_20240202_1659_30/00000000/Sample_005_00003074.tiff, ...
id: id0, id1, id2, id3, id4, ...
gate: Default, Default, Default, Default, Default, ...
Gates: Default
Selected gate: Default
Images matching gate: 10000
Saving processed images to directory: /Users/tischer/Downloads/demo_data/images-processed-2024-02-27-13-12
Number of images to be processed: 10000
Files processed: 1300/10000; time ( spent, left, task ) [ s ]: 42, 287, 0.0330; memory: 90MB of 5461MB (1%)
```

**Comment by tischi** [comment]
@gabrielpan147 to narrow down the issue, does it work for you starting from within the GUI, using `Plugins › BD CellView › Process BD CellView Images Headless` and selecting the JSON file?

**Comment by tischi** [comment]
Ok, interesting, for me it also exits after one image:

`/Users/tischer/Desktop/Fiji/Fiji.app/Contents/MacOS/ImageJ-macosx --headless --run "Process BD CellView Images Headless" "settingsFile='/Users/tischer/Downloads/demo_data/json/batch_2channels.json'"`

So, "good" I can reproduce it, I will try to find out what the issue is...

**Comment by gabrielpan147** [comment]
@tischi Yes it works within the GUI for me. Although it is still not generating a separate folder for storing converted images, every other functions work perfectly. Initially I suppose it is due to the Ubuntu(which I run the headless) vs MacOS(which I test with GUI), but it seems not the case...
If there is no warning or error message, I suppose the plugin actually crash due to some reason? An interesting fact is that for the several test I have tried, the plugin exited after generating different number of images. Sometime only 1, sometime around 10, sometime zero...

**Comment by gabrielpan147** [comment]
I just noticed if it works properly within Java IDE, would it due to some compiling bugs? I'm not familiar with Java or Javascript so IDk if it helps

**Comment by tischi** [comment]
> I just noticed if it works properly within Java IDE, 

Yeah, for me, too...using IntelliJ.

Are you also getting these errors when running from command line?

```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
Please visit http://www.java.com for information on installing Java.

The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
Please visit http://www.java.com for information on installing Java.
```

**Comment by tischi** [comment]
I am asking [in the forum....](https://forum.image.sc/t/fiji-quitting-when-running-headless/92758).

**Comment by gabrielpan147** [comment]
> > I just noticed if it works properly within Java IDE,
> 
> Yeah, for me, too...using IntelliJ.
> 
> Are you also getting these errors when running from command line?
> 
> ```
> The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
> Please visit http://www.java.com for information on installing Java.
> 
> The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
> Please visit http://www.java.com for information on installing Java.
> ```

No actually I did not see this, for me it just got crashed quietly...

**Comment by tischi** [comment]
This is very weird, I tried many things but nothing helps...let's see if the folks on the forum have an idea...

**Comment by gabrielpan147** [comment]
> This is very weird, I tried many things but nothing helps...let's see if the folks on the forum have an idea...

I just quickly go through the internet, it seems that this error only occurs on MacOS?

**Comment by tischi** [comment]
> I just quickly go through the internet, it seems that this error only occurs on MacOS?

Which error do you mean?

**Comment by gabrielpan147** [comment]
> The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
> Please visit http://www.java.com for information on installing Java.

The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
Please visit http://www.java.com for information on installing Java.

This one.

**Comment by gabrielpan147** [comment]
> > I just quickly go through the internet, it seems that this error only occurs on MacOS?
> 
> Which error do you mean?
This is the error I mentioned:
The operation couldn’t be completed. Unable to locate a Java Runtime that supports (null).
Please visit http://www.java.com for information on installing Java.

**Comment by tischi** [comment]
@gabrielpan147 would you have time to try some of the things that Curtis suggested here?

https://forum.image.sc/t/fiji-quitting-when-running-headless/92758/2

**Comment by gabrielpan147** [comment]
@tischi  Hello,
I tried to add the debug flag, and I think there's no useful information provided. I have attached the output log [here](https://hkustconnect-my.sharepoint.com/:u:/g/personal/epanab_connect_ust_hk/EQXu78jpdB1KoP-Pr9IxgpIBlZhksOTBzPQr3IBw8a2PNw?e=Dhibx3) FYI.
I tried the --forbid-single-instance flag and it did not work as well. I can not use the jstack tool for the time being so I will try it later. For the exit code the program returned, it was 0.

**Comment by tischi** [comment]
created branch `issue25`

**Comment by tischi** [comment]
@gabrielpan147 can you try this?

`/Users/tischer/Desktop/Fiji/Fiji.app/Contents/MacOS/ImageJ-macosx --run "Process BD CellView Images Headless" "settingsFile='/Users/tischer/Downloads/demo_data/json/batch_2channels.json'"`

Essentially just removing the `--headless`? This should launch the Fiji GUI and then automatically execute the code. 
Does this work?

**Comment by tischi** [comment]
Hi @gabrielpan147, I think I found the issue (see forum thread); if you update your Fiji it should run through now.

**Comment by gabrielpan147** [comment]
Hello @tischi , I just tried on my machine and it worked! Thank you for your help!!!
